services:
  local-llm:
    image: ollama/ollama:0.30.10
    volumes:
      - local-llm:/root/.ollama
    ports:
      - "11434:11434"
    # Comment out this deploy section if you don't use any GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  local-llm-webui:
    image: ghcr.io/open-webui/open-webui:0.9.4 # newer version (0.9.5 or more) failed web search
    volumes:
      - local-llm-webui:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - WEBUI_AUTH=False
      - ENABLE_OLLAMA_API=True
      - OLLAMA_BASE_URL=http://local-llm:11434
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - SEARXNG_QUERY_URL=http://web-search-proxy:8080/search?q=<query>
    # Comment out this deploy section if you don't use any GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  web-search-proxy:
    build: ./serxng
    ports:
      - ":8080"

volumes:
  local-llm:
  local-llm-webui:
